### ISSUE TITLE
Trying to play with your tool, missing dependencies

### ISSUE THREAD

**Issue by forceworks** [sgtsnacks-64/JustAskIt#10]
Installing the unmanaged solution 1.0.0.1 on a clean dataverse it fails with the following missing dependencies

<MissingDependency><Required type=\"300\" schemaName=\"ans_anscomponentlibraryheadersfooters_83614\" displayName=\"ANS Component Library - Headers &amp; Footers\" solution=\"Active\" /><Dependent type=\"300\" schemaName=\"ans_newrequest_91694\" displayName=\"New Request\" /></MissingDependency>
<MissingDependency><Required type=\"300\" schemaName=\"cr0a0_ansformscomponentlibrary_41d2f\" displayName=\"ANS - Forms Component Library\" solution=\"Active\" /><Dependent type=\"300\" schemaName=\"ans_newrequest_91694\" displayName=\"New Request\" /></MissingDependency>
<MissingDependency><Required type=\"connectionreference\" displayName=\"new_sharedopenaigpt4ip_d02bc\" solution=\"Active\" id.connectionreferencelogicalname=\"new_sharedopenaigpt4ip_d02bc\" /><Dependent type=\"29\" displayName=\"Prompt and Response\" id=\"{61df065d-207b-ee11-8179-002248004ea0}\" /></MissingDependency>

**Comment by sgtsnacks-64** [comment]
Thanks for logging this issue @forceworks, just taking a look now, looks like we jumped a bit ahead of ourselves on feature I was working on.

I'll be updating the repo shortly with the dependency removed :)

**Comment by sgtsnacks-64** [comment]
@forceworks  we've now removed the dependencies and repushed the solution. Can you try again and let us know the outcome?

@jondoesflow

**Comment by jondoesflow** [comment]
Issue resolved

**Comment by sgtsnacks-64** [comment]
@jondoesflow awaiting confirmation from @forceworks

**Comment by jondoesflow** [comment]
Fair enough !
