### ISSUE TITLE
LookUp columns for Rules and Prompt Rules display an unhelpful autonumber field

### ISSUE THREAD

**Issue by sgtsnacks-64** [sgtsnacks-64/JustAskIt#13]
When specifying Rules in the Prompt Rule intersection table, specifying rules only displays the Rule's Autonumber field and not the text of the rule. This is not helpful when adding new prompt rules:

![image](https://github.com/sgtsnacks-64/JustAskIt/assets/96265020/79a101ec-f2c2-48b2-9219-8090a42fdf0c)

**Comment by jondoesflow** [comment]
Hey @sgtsnacks-64 I have made the changes to this. I have left the Rule table pretty much as is, except I have renamed the Rule Ref column to Rule Text, and changed it from an autonumber to Text.  There is now a flow that will run and update the Rule's primary field to the Rule Text field (original)
