### ISSUE TITLE
Missing dependencies

### ISSUE THREAD

**Issue by realwillwright** [sgtsnacks-64/JustAskIt#19]
Hi,

I was attempting to install the solution 'JustAskIt_1_0_0_8' and encountered the missing dependencies, please see attached.

[log.txt](https://github.com/sgtsnacks-64/JustAskIt/files/14309275/log.txt)

**Comment by sgtsnacks-64** [comment]
Dependencies resolved, will be pulling tomorrow morning! Thanks for bringing it to our attention @realwillwright!
