### ISSUE TITLE
Generate sample configuration data to be supplied with release

### ISSUE THREAD

**Issue by sgtsnacks-64** [sgtsnacks-64/JustAskIt#6]
For first release, we need to supply configuration data containing:

Models
Example Prompts
Example Requests
Example Responses
Example Feedback

This will help initiate the system for the user when first installing and will serve as a tutorial.

**Comment by jondoesflow** [comment]
@sgtsnacks-64 I have added this data as an exported zip file - https://github.com/sgtsnacks-64/JustAskIt/blob/main/justaskit%20data.zip

User would need to import via pac tool cmt
