### ISSUE TITLE
Landing screen for model driven app

### ISSUE THREAD

**Issue by sgtsnacks-64** [sgtsnacks-64/JustAskIt#9]
The model driven app could have a landing screen as a custom page to help guide users on what steps to take to use JustAskIt

This is low priority

**Comment by jondoesflow** [comment]
Hey @sgtsnacks-64 

What should we have on the landing screen ? I'm thinking

1. Brief description of what JustAskIt is
2. Steps on how to use it

Anything else?

**Comment by sgtsnacks-64** [comment]
Yeah 100%. We can also link into the different entity forms as well to get users going

**Comment by sgtsnacks-64** [comment]
![image](https://github.com/sgtsnacks-64/JustAskIt/assets/96265020/53f06614-a2c5-456a-a6ff-020e36cf15db)
Initial Landing Page created - Marking as Ready for PR
